# Generated by Django 5.1.7 on 2026-02-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_register_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
