# Generated by Django 5.1.7 on 2026-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_register_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
