# Generated by Django 5.1.7 on 2026-03-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hostevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostevent',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted')], default='NEW', max_length=20),
        ),
    ]
