from django.urls import path
from . views import register_user,login_user
from . import views
from .views import *
from .views import test_email
urlpatterns=[
    path('register/',register_user,name="register"),
    path("login/", login_user,name="login"),
    path("create-event/", views.create_event),
    path("events/", views.public_events),
    path('api/events/', views.get_all_events),
    path("organizer-events/", views.organizer_events),
    path("update-event/<int:pk>/", views.update_event),
    path("delete-event/<int:pk>/", views.delete_event),
    path("update-profile/", views.update_profile),
    path("request-deletion/", views.request_account_deletion),
    path("event/<int:id>/", views.get_event_detail),
    path("create-booking/", views.create_booking),
    path("user-bookings/<int:user_id>/", views.user_bookings),
    path("booking/<int:booking_id>/", views.booking_detail),
    path("cancel-booking/<int:booking_id>/", views.cancel_booking),
    path("all-bookings/", views.all_bookings),
    path("organizer-dashboard/", organizer_dashboard),
    path('user-dashboard/', views.user_dashboard),
    path("organizer-bookings/", organizer_bookings),
    path("search-events/", search_events),
    path('admin-dashboard/', admin_dashboard_stats),
    path("bookings-chart/", bookings_per_month),
    path("admin-users/", get_all_users),
    path("search-users/", search_users),
    path("toggle-user-status/<int:user_id>/", toggle_user_status),
    path("user-bookings/<int:user_id>/", user_booking_history),
    path("delete-user/<int:user_id>/", delete_user),
    path("admin-organizers/", views.admin_organizers),
    path("approve-organizer/<int:id>/", views.approve_organizer),
    path("toggle-organizer/<int:id>/", views.toggle_organizer),
    path("organizer-event/<int:id>/", views.organizer_event),
    path("approve-delete/<int:id>/", views.approve_delete),
    path("admin-events/", views.admin_events),
    path("approve-event/<int:id>/", views.approve_event),
    path("reject-event/<int:id>/", views.reject_event),
    path("update_event/<int:id>/",views.update_event),
    path("delete-event/<int:pk>/", views.delete_event),
    path("admin-bookings/", views.admin_bookings),
    path("admin-revenue/", admin_revenue),
    path("ai-analytics/", ai_analytics),
    path("chatbot/",chatbot),
    path("test-email/", test_email),
    path("host-event/", host_event),
    path("host-event-list/", host_event_list),
    path("host-event-count/",host_event_notification_count),
    path("host-events/",host_events),
    path("contacted-host-event/<int:pk>/",contacted_host_event),
    path("approve-host-event/<int:pk>/",approve_host_event),
    path("add-wishlist/", views.add_wishlist),
    path("remove-wishlist/<int:event_id>/<int:user_id>/", views.remove_wishlist),
    path("my-wishlist/<int:user_id>/", views.my_wishlist),
    path("event-reminders/<int:user_id>/",event_reminders),
    path("recommended-events/<int:user_id>/",views.recommended_events),
    path("popular_this_week/",popular_this_week),
    path("featured-events/", views.featured_events),
    path("upcoming-events/", views.upcoming_events),
    path("forgot-password/", views.forgot_password),
    path("reset-password/<uid>/", views.reset_password),
    path("subscribe-newsletter/", views.subscribe_newsletter),
    path("admin-register/", admin_register),
    path("admin-login/", admin_login),
]